import AuthLayout from "@/components/layout/AuthLayout";
import "../globals.css";
import DashboardLayout from "@/components/layout/DashboardLayout";
import Sidebar from "@/components/UI/Sidebar";

export const metadata = {
  title: "Diajak Alolgamerz Web3",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex antialiased">
        <Sidebar />
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
